blog/urls.py
from django.urls import path
from blog.views import *
from django.conf import settings
from django.conf.urls.static import static
from blog.feeds import LatestEntriesFeed
app_name = 'blog'

urlpatterns = [
    path('',blog_view, name='index'),
    # path('single/',blog_single, name='single'),
    path('<int:pid>',blog_single, name='single'),
    path('category/<str:cat_name>',blog_view, name='category'),
    path('tag/<str:tag_name>',blog_view, name='tag'),
    path('author/<str:author_username>',blog_view,name='author'),
    path('search/',blog_search,name='search'),
    
    # path('post-<int:pid>',test, name='test'), 
    path("rss/feed/", LatestEntriesFeed()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_course/urls.py
from django.contrib.sitemaps.views import sitemap
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
import debug_toolbar
from website import views
from django.http.response import HttpResponseRedirect
# from django.contrib.auth.urls
from django.urls import re_path
from django.conf import settings
from django.views.generic.base import TemplateView
sitemaps = {
    "static": StaticViewSitemap,
    'blog':BlogSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls')),
    path('blog/',include('blog.urls')),
    path('accounts/',include('accounts.urls')),
    path('summernote/',include('django_summernote.urls')),
    path("sitemap.xml",sitemap,{"sitemaps": sitemaps},name="django.contrib.sitemaps.views.sitemap",),
    path('robots.txt',include('robots.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('captcha/', include('captcha.urls')),
    # re_path(r'^', TemplateView.as_view(template_name='../templates/website/coming_soon'), name='maintenance'),
    path("accounts/", include("django.contrib.auth.urls")),

    # re_path(r'^', views.maintenance, name='maintenance')
    # urlpatterns.insert(0, re_path(r'^', TemplateView.as_view(template_name='../path/maintenance.html'), name='maintenance'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# handler404 = 'website.views.handler404'


#-----------------------------------------------------------------------------------------
#  404 page   MAINTENANCE_MODE


# if settings.MAINTENANCE_MODE:
#     urlpatterns.insert(0, re_path(r'^', TemplateView.as_view(template_name='../templates/website/coming_soon.html'), name='maintenance'))

website/urls.py
from django.urls import path
from website.views import *

app_name = 'website'

urlpatterns = [
    path('',index_view, name='index'),
    path('about', about_view, name='about'),
    path('contact',contact_view, name='contact'),

    path('newsletter',newsletter_view,name='newsletter'),
    path('coming_soon', coming_soon_view, name='coming_soon'),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.urls import reverse
# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Post(models.Model):
    image=models.ImageField(upload_to='blog/',default='blog/defalt.jpg')
    author=models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    title=models.CharField(max_length=255)
    content=models.TextField()
    tags = TaggableManager()
    category=models.ManyToManyField(Category)
    counted_views=models.IntegerField(default=0)
    status=models.BooleanField(default=False)
    login_require=models.BooleanField(default=False)
    published_date=models.DateTimeField(null=True)
    created_date=models.DateTimeField(auto_now_add=True)
    updated_date=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('created_date',)
        # verbose_name='Post'
        # verbose_name_plural='Posts'

    def __str__(self):
        return " {} ".format(self.title)
    def get_absolute_url(self):
        return reverse('blog:single',kwargs={'pid':self.id})

class Comment(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE)
    name=models.CharField(max_length=255)
    email=models.EmailField()
    subject=models.CharField(max_length=255)
    message=models.TextField()
    approved=models.BooleanField(default=False)
    created_date=models.DateTimeField(auto_now_add=True)
    updated_date=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('created_date',)

    def __str__(self):
        return self.name
    

blog/forms.py
from django import forms
from blog.models import Comment
# from captcha.fields import CaptchaField



class CommentForm(forms.ModelForm):
    # captcha = CaptchaField()
    class Meta :
        model=Comment
        fields=['post','name','email','subject','message']

blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from blog.models import Post
from django.utils import timezone
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from blog.models import Comment
from blog.forms import CommentForm
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect
from blog.models import Post
# Create your views here.
def blog_view(request,**kwargs):
    posts=Post.objects.filter(status=1,published_date__lte=timezone.now())
    if kwargs.get('cat_name')!=None:
        posts=posts.filter(category__name=kwargs['cat_name'])
    if kwargs.get('author_username')!=None:
        posts=posts.filter(author__username=kwargs['author_username'])
    if kwargs.get('tag_name')!=None:
        posts=posts.filter(tags__name__in=[kwargs['tag_name']])
    posts=Paginator(posts,6)
    try:
        page_number=request.GET.get('page')
        posts=posts.get_page(page_number)
    except PageNotAnInteger:
        posts=posts.get_page(1)
    except EmptyPage :
        posts=posts.get_page(1)
    context = {'posts': posts}
    return render(request,'blog/blog-home.html',context)

def blog_single(request,pid):   
    if request.method=='POST':
        form =CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request,messages.SUCCESS,"your comment submited")
        else:
            messages.add_message(request,messages.ERROR,"your comment didnt submited")  
    post = get_object_or_404(Post,pk=pid,status=1,published_date__lte=timezone.now())
    post.counted_views += 1
    post.save()
    previous_post = Post.objects.filter(id__lt=pid,status=1,published_date__lte=timezone.now()).order_by('-id').first()
    next_post = Post.objects.filter(id__gt=pid,status=1,published_date__lte=timezone.now()).order_by('id').first()
    if not post.login_require:
        comments=Comment.objects.filter(post=post.id,approved=True).order_by('-created_date')
        form=CommentForm()
        context={'post':post,'previous_post': previous_post,'next_post': next_post,'comments':comments,'form':form}
        return render(request,'blog/blog-single.html',context)
    else:
        return HttpResponseRedirect(reverse('accounts:login'))

def blog_category(request,cat_name):
    posts=Post.objects.filter(status=1)
    posts=posts.filter(category__name=cat_name)
    context={'posts':posts}
    return render(request,'blog/blog-home.html',context)



def blog_search(request):
    posts=Post.objects.filter(status=1,published_date__lte=timezone.now())

    # print(request.__dict__)
    if request.method=='GET':
        # print(request.GET.get('s'))
        if s:=request.GET.get('s'):
            posts=posts.filter(content__contains=s)
    #     print('get request')
    context={'posts':posts}
    return render(request,'blog/blog-home.html',context)

templates/blog/blog-home.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %} 

{% block content %}

    <!-- Header Start -->
    <div class="container-fluid page-header">
        <div class="container">
            <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 400px">
                <h3 class="display-4 text-white text-uppercase">Blog</h3>
                <div class="d-inline-flex text-white">
                    <p class="m-0 text-uppercase"><a class="text-white" href="{% url 'website:index' %}">Home</a></p>
                    <i class="fa fa-angle-double-right pt-1 px-3"></i>
                    <p class="m-0 text-uppercase"><a class="text-white" href="{% url 'blog:index' %}">Blog</a></p>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->


    <!-- Blog Start -->
    <div class="container-fluid py-5">
        <div class="container py-5">
            <div class="row">
                <div class="col-lg-8">
                    <div class="row pb-3">
                        {% for post in posts %}
                        <div class="col-md-6 mb-4 pb-2">
                            <div class="blog-item">
                                <div class="position-relative">
                                    <img class="img-fluid w-100" src="{{post.image.url}}" alt="">
                                    <div class="blog-date">
                                        <small class="text-white text-uppercase">{{post.published_date|date:"y/m/d"}}</small>
                                        <small class="text-white">views:{{post.counted_views}}</small>
                                    </div>
                                </div>
                                <div class="bg-white p-4">
                                    {% for cat in post.category.all %}
                                    <a href="{% url 'blog:category' cat_name=cat.name %}"> {{cat.name}}</a>{% if not forloop.last %},{% endif %}
                                    {% endfor %}
                                    <div class="d-flex mb-2">
                                        <a class="text-primary text-uppercase text-decoration-none" href="{% url 'blog:author' author_username=post.author.username %}">{{post.author}}</a>
                                        <span class="text-primary px-2">|</span>
                                        <a class="text-primary text-uppercase text-decoration-none" href="{% url 'blog:single' pid=post.id %}">{{post.title}}</a>
                                    </div>
                                    <a class="h5 m-0 text-decoration-none" href="#">{{post.content|truncatewords:4}} </a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        <div class="col-12">
                            <nav aria-label="Page navigation">
                                <ul class="pagination pagination-lg justify-content-center bg-white mb-0" style="padding: 30px;">
                                    {% if posts.has_previous %}
                                  <li class="page-item">
                                    <a class="page-link" href="?page={{ posts.previous_page_number }}" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                        <button class="sr-only">Previous</button>
                                    </a>
                                  </li>
                                  {% endif %}
                                  {% for i in posts.paginator.page_range %}
                                  {% if posts.number == i %}
                                  <li class="page-item active"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
                                  {% else %}
                                  <li class="page-item"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
                                  {% endif %}
                                  {% endfor %}
                                  {% if posts.has_next %}
                                  <li class="page-item">
                                    <a class="page-link" href="?page={{ posts.next_page_number }}" aria-label="Next">
                                      <span aria-hidden="true">&raquo;</span>
                                      <button class="sr-only">Next</button>
                                    </a>
                                  </li>
                                  {% endif %}
                                </ul>
                              </nav>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 mt-5 mt-lg-0">
                    {% include 'blog/blog-programmer.html' %}
    
                    {% include 'blog/blog-search.html' %}
                
                    {% postcategories %}
    
                    {% latestposts %}
                </div>
            </div>
        </div>
    </div>
    <!-- Blog End -->

{% endblock %}

templates/blog/blog-post-categories.html
<!-- Category List -->
<div class="mb-5">
    <h4 class="text-uppercase mb-4" style="letter-spacing: 5px;">Categories</h4>
    <div class="bg-white" style="padding: 30px;">
        {% for name,count in categories.items %}
        <ul class="list-inline m-0">
            <li class="mb-3 d-flex justify-content-between align-items-center">
                <a class="text-dark" href="{% url 'blog:category' cat_name=name %}"><i class="fa fa-angle-right text-primary mr-2"></i>{{name}}</a>
                <span class="badge badge-primary badge-pill">{{count}}</span></a></li>
        </ul>
        {% endfor %}
    </div>
</div>

templates/blog/blog-programmer.html
{% load static %}


<!-- Author Bio -->
<div class="d-flex flex-column text-center bg-white mb-5 py-5 px-4">
    <img src="{% static 'img/user.jpg' %}" class="img-fluid mx-auto mb-3" style="width: 100px;">
    <h3 class="text-primary mb-3">Mohammad Parsa Mohajeri</h3>
    <p>The developer of this website is me. like my design? you can contact to my github below</p>
    <div class="d-flex justify-content-center">
        <a class="text-primary px-2" href="">
            <a href="https://github.com/ParsaMohajeri"><i class="fab fa-github"></i></a>
    </div>
</div>

templates/blog/blog-recent-posts.html
{% load static %}
{% load humanize %}
{% load blog_tags %}
<!-- Recent Post -->
<div class="mb-5">
    
    <h4 class="text-uppercase mb-4" style="letter-spacing: 5px;">Recent Post</h4>
    {% for post in posts %}
    <a class="d-flex align-items-left text-decoration-none bg-white mb-3" href="">
        <img class="img-fluid-recent" src="{{post.image.url}}" alt="">
        <div class="pl-3">
            <h6 href="{% url 'blog:single' pid=post.id %}" class="m-1">{{post.title}}</h6>
            <small>{{post.published_date|naturaltime}}</small>
        </div>
    </a>
    {% endfor %}
</div>

templates/blog/blog-search.html
<div class="mb-5">
    <form class="search-form" class="input-group-text bg-primary border-primary text-white" action="{% url 'blog:search' %}" method="get">
        <input placeholder="Search Posts" name="s" type="text" class="form-control p-4" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" >
        <button class="input-group-text bg-primary border-primary text-white" type="submit"><i class="fa fa-search"></i></button>
    </form>
</div>

templates/blog/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load blog_tags %}
{% block content %}

    <!-- Header Start -->
    <div class="container-fluid page-header">
        <div class="container">
            <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 400px">
                <h3 class="display-4 text-white text-uppercase">{{post.title}}</h3>
                <div class="d-inline-flex text-white">
                    <p class="m-0 text-uppercase"><a class="text-white" href="{% url 'website:index' %}">Home</a></p>
                    <i class="fa fa-angle-double-right pt-1 px-3"></i>
                    <p class="m-0 text-uppercase"><a class="text-white" href="{% url 'blog:index' %}">Blog</a></p>
                    <i class="fa fa-angle-double-right pt-1 px-3"></i>
                    <p class="m-0 text-uppercase"><a class="text-white" href="{{post.id}}">{{post.title}}</a></p>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->


    <!-- Blog Start -->
    <div class="container-fluid py-5">
        <div class="container py-5">
            <div class="row">
                <div class="col-lg-8">
                    <!-- Blog Detail Start -->
                    <div class="pb-3">
                        <div class="blog-item">
                            <div class="position-relative">
                                <img class="img-fluid w-100" src="{{post.image.url}}" alt="">
                                <div class="blog-date">
                                    <small class="text-white text-uppercase">{{post.published_date|date:"y/m/d"}}</small>
                                    <small class="text-white">views:{{post.counted_views}}</small>
                                </div>
                            </div>
                        </div>
                        <div class="bg-white mb-3" style="padding: 30px;">
                            <div class="d-flex mb-3">
                                <a class="text-primary text-uppercase text-decoration-none" href="">{{post.author}}</a>
                                <span class="text-primary px-2">|</span>
                                <a class="text-primary text-uppercase text-decoration-none" href="">{{post.counted_views}}</a>
                            </div>
                            <h2 class="mb-3">{{post.title}}</h2>
                            <p>{{post.content}}</p>
                        </div>
                    </div>
                    <!-- Blog Detail End -->
    
                    <!-- Comment List Start -->
                    <div class="bg-white" style="padding: 30px; margin-bottom: 30px;">
                        <h4 class="text-uppercase mb-4" style="letter-spacing: 5px;">{{ comments|length }} Comments</h4>
                        {% for comment in comments %}
                            <div class="media mb-4">
                                <img src="{% static 'img/user.jpg' %}" alt="Image" class="img-fluid mr-3 mt-1" style="width: 45px;">
                                <div class="media-body">
                                    <h6><a href="">{{comment.name}}</a> <small><i>{{comment.created_date|naturaltime}}</i></small></h6>
                                    <p>{{comment.subject}}</p>
                                    <p>{{comment.message}}</p>
                                </div>

                            </div>
                            {% empty %}
                            <p>no comments be the first</p>
                        {% endfor %}
                    </div>
                    <!-- Comment List End -->
    
                    <!-- Comment Form Start -->
                    <div class="bg-white mb-3" style="padding: 30px;">
                        <h4 class="text-uppercase mb-4" style="letter-spacing: 5px;">Leave a comment</h4>
                        <form method="post" action="{% url 'blog:single' pid=post.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="post" value={{post.id}}>
                            {% if request.user.is_authenticated %}
                                <div class="form-group">
                                    <input type="hidden" value={{request.user.first_name} placeholder="Enter Name"  class="form-control" name="name">
                                </div>
                                <div class="form-group">
                                    <input type="hidden" name="email" placeholder="Enter email address" value={{request.user.email}} class="form-control" name="email">
                                </div>
                            {% else %}
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input type="text" class="form-control" name="name">
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email"  class="form-control" name="email">
                            </div>
                            {% endif %}
                            <div class="form-group">
                                <label for="subject">Subject</label>
                                <input type="text" class="form-control" name="subject">
                            </div>
    
                            <div class="form-group">
                                <label for="message">Message</label>
                                <textarea name="message" cols="30" rows="5" class="form-control"></textarea>
                            </div>
                            <div class="form-group mb-0">
                                <button  type="submit" >
                                <input type="submit" value="Leave a comment"
                                    class="btn btn-primary font-weight-semi-bold py-2 px-3">
                               </button>
                            </div>
                        </form>
                    </div>
                    <!-- Comment Form End -->
                </div>
    
                <div class="col-lg-4 mt-5 mt-lg-0">
                    {% include 'blog/blog-programmer.html' %}
    
                    {% include 'blog/blog-search.html' %}
                
                    {% postcategories %}
    
                    {% latestposts %}
    
                    {% include 'blog/blog-tags.html' %}
                </div>
            </div>
        </div>
    </div>
    <!-- Blog End -->
{% endblock %}

templates/blog/blog-tags.html
<!-- Tag Cloud -->
<div class="mb-5">
    <h4 class="text-uppercase mb-4" style="letter-spacing: 5px;">Tags</h4>
    <div class="d-flex flex-wrap m-n1">
        {% for tag in post.tags.all %}
        <a href="{% url 'blog:tag' tag_name=tag.name %}" class="btn btn-light m-1">{{tag.name}}</a>
        {% endfor %}

    </div>
</div>